- hosts: localhost
  vars:
    PETCLINIC_VERSION: "0.0.1"
    
  tasks:
  - name: install docker-py
    pip: name=docker-py version=1.2.1
    become: yes
    become_method: sudo
    
  - name: create docker directory
    file: path=~/DevOps/my_docker state=directory mode=0755
    
  - name: create Dockerfile from Jinga2 template
    become: yes
    become_method: sudo
    template: src=~/DevOps/Dockerfile.j2 dest=~/my_docker/Dockerfile 
    
  - name: create image
    docker_image: path="/home/ec2-user/dock" name="petclin" state="present" tag="ll" 
