- hosts: localhost
  tasks:
  - name: install docker-py
    pip: name=docker-py version=1.2.1
    become: yes
    become_method: sudo
  - name: create image
    docker_image: path="/home/ec2-user/dock" name="petclin" state="present" tag="ll" 
