- hosts: localhost
  vars:
    PETCLINIC_VERSION: "0.0.1"
    
  tasks:
  - name: install docker-py
    pip: name=docker-py version=1.2.1
    become: yes
    become_method: sudo
    
  - name: create docker directory
    file: path=/home/ec2-user/DevOps/my_docker state=directory mode=0755
    
  - name: create Dockerfile from Jinga2 template
    template: src=/home/ec2-user/DevOps/Dockerfile.j2 dest=/home/ec2-user/DevOps/my_docker/Dockerfile 
    
  - name: create image
    docker_image: path="/home/ec2-user/DevOps/my_docker/" name="petclin" state="present" tag="ll" 
