- hosts: localhost
  tasks:
  - name: install git
    yum: name=git state=latest
    become: yes
    become_method: sudo
  - name: clone petclinic
    git: repo=https://github.com/shimib/spring-petclinic.git dest=~/spring-petclinic
  - name: clone course
    git: repo=https://github.com/shimib/course_cis.git dest=~/course update=no
  - name: create tmp dir
    file: path=~/tmp state=directory
  - name: download and extract maven
    unarchive: src=http://apache.mivzakim.net/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz dest=~/tmp copy=no mode=755
  - name: set env m2_home
    lineinfile: dest=/home/ec2-user/.bash_profile regexp="^M2_HOME.*" line="M2_HOME=/home/ec2-user/tmp/apache-maven-3.3.9" insertbefore="^PATH="
